### ISSUE TITLE
checkov GH workflow permission

### ISSUE THREAD

**Issue by matt-FFFFFF** [Azure/tfmod-scaffold#12]
Checkov fails on GH actions workflow files in this repo.

We need to put in token permissions:

e.g.

```yaml
permissions:
  contents: write
  pull-requests: read
```
